export const blastNFTs = [
  {
    tokenId: 0,
    name: 'Gunner',
    image: 'images/nfts/blast/blast-gunner.png',
    chain: 'Blast',
    chainId: 81457,
    contract: '0xaa9E4A3E0b567C3ed9B945ec4b045157246370a0',
    price: 0.0006,
    minted: false,
    supply: 4000,
  },
  {
    tokenId: 1,
    name: 'Big fun',
    image: 'images/nfts/blast/blast-big-fun.png',
    chain: 'Blast',
    chainId: 81457,
    contract: '0x8fDbeAf16505A0b98202A80315ceEE5bCBCE14d4',
    price: 0.0004,
    minted: false,
    supply: 3000,
  },
  {
    tokenId: 2,
    name: 'Blaster',
    image: 'images/nfts/blast/blast-blaster.png',
    chain: 'Blast',
    chainId: 81457,
    contract: '0xCA0E3e27b48677dc0EC6C5FC3987D786B68C7666',
    price: 0.0003,
    minted: false,
    supply: 0,
  },
  {
    tokenId: 3,
    name: 'Earn more ETH',
    image: 'images/nfts/blast/blast-earn-more-eth.png',
    chain: 'Blast',
    chainId: 81457,
    contract: '0x73DE17F387DECAfcFF5aD97dB4f488BfE0F1b33A',
    price: 0.0003,
    minted: false,
    supply: 0,
  },
  // {
  //   tokenId: 4,
  //   name: 'Fighter',
  //   image: 'images/nfts/blast/blast-fighter.png',
  //   chain: 'Blast',
  //   chainId: 81457,
  //   contract: '',
  //   price: 0.0003,
  //   minted: false,
  //   supply: 0,
  // },
  // {
  //   tokenId: 5,
  //   name: 'Pixel Blast',
  //   image: 'images/nfts/blast/blast-pixelblast.png',
  //   chain: 'Blast',
  //   chainId: 81457,
  //   contract: '',
  //   price: 0.0003,
  //   minted: false,
  //   supply: 0,
  // },
  // {
  //   tokenId: 6,
  //   name: 'Shopping bag',
  //   image: 'images/nfts/blast/blast-shopping-bag.png',
  //   chain: 'Blast',
  //   chainId: 81457,
  //   contract: '',
  //   price: 0.0003,
  //   minted: false,
  //   supply: 0,
  // },
  // {
  //   tokenId: 7,
  //   name: 'Blast',
  //   image: 'images/nfts/blast/blast.png',
  //   chain: 'Blast',
  //   chainId: 81457,
  //   contract: '',
  //   price: 0.0003,
  //   minted: false,
  //   supply: 0,
  // },
];
