// Generated by Xata Codegen 0.18.0. Please do not edit.
import {
  BaseClientOptions,
  buildClient,
  SchemaInference,
  XataRecord,
} from '@xata.io/client';

const tables = [
  {
    name: 'createdNfts',
    columns: [
      { name: 'name', type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'image', type: 'string' },
      { name: 'address', type: 'string' },
      { name: 'chain', type: 'string' },
      { name: 'tokenId', type: 'int' },
    ],
  },
  {
    name: 'mints',
    columns: [
      { name: 'address', type: 'string' },
      { name: 'contract', type: 'string' },
      { name: 'chain', type: 'string' },
      { name: 'tokenId', type: 'int' }
    ],
  },
  {
    name: 'deployments',
    columns: [
      { name: 'address', type: 'string' },
      { name: 'contract', type: 'string' },
      { name: 'blockchain', type: 'string' }
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type CreatedNfts = InferredTypes['createdNfts'];
export type CreatedNftsRecord = CreatedNfts & XataRecord;

export type Mints = InferredTypes['mints'];
export type MintsRecord = Mints & XataRecord;

export type Deployments = InferredTypes['deployments'];
export type DeploymentsRecord = Deployments & XataRecord;

export type DatabaseSchema = {
  createdNfts: CreatedNftsRecord;
  mints: MintsRecord;
  deployments: DeploymentsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    'https://Soulmans-Workspace-mk3gtt.eu-central-1.xata.sh/db/mint-heaven',
  enableBrowser: true,
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
